i=imread('einestine.jpg');
subplot(2,3,1);
imshow(i);
title('Original Image');
A=rgb2gray(i);
subplot(2,3,2);
imshow(A);
title('Gray Scale Image');
prewitt=edge(A,'prewitt');
subplot(2,3,3);
imshow(prewitt);
title('Prewiit');
sobel=edge(A,'sobel');
subplot(2,3,4);
imshow(sobel);
title('Sobel');
roberts=edge(A,'roberts');
subplot(2,3,5);
imshow(roberts);title('Roberts');